services:
  myapp:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/home/app
    #   - /home/app/node_modules
    ports:
      - "5173:5173"
      # - "/c:/Users/David/Documents/Programacion/pruebaDocker/dockerwebvite:/home/app"
