services:
  myapp:
    container_name: myapp3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:80"
      # - "/c:/Users/David/Documents/Programacion/pruebaDocker/dockerwebvite:/home/app"
