services:
  myapp:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - "3004:80"
      # - "/c:/Users/David/Documents/Programacion/pruebaDocker/dockerwebvite:/home/app"
