name: Build the project
on:
    push:
        branches:
            - main
jobs:
    buils:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker BUildx
              uses: docker/setup-buildx-action@v2
            
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_USERNAME }}
            - name: Build and Push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true                                                                                                                                                
                tags: ${{secrets.DOCKER_USERNAME }}/myapp3